spring:
  rabbitmq:
    host: 192.168.109.130
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1