spring:
  rabbitmq:
    host: 192.168.109.130
    username: admin
    password: admin
    virtual-host: /
    port: 5672
    publisher-confirm-type: simple
    publisher-returns: true
    template:
      mandatory: true